### ISSUE TITLE
Version 1.70 intellisense does not work

### ISSUE THREAD

**Issue by tohsaka888** [microsoft/typescript-styled-plugin#159]
### Version 1.65
![image](https://user-images.githubusercontent.com/58759688/145525889-43b23a3a-17e0-4f4d-bf1d-d0079c985495.png)
### Version 1.70
![image](https://user-images.githubusercontent.com/58759688/145525968-846b5529-2b54-45c6-8565-267aa4e5cf89.png)
Is there any mistake in my operation?QAQ

**Comment by BignonAG** [comment]
No there is no mistake. The previous version of styled component plugin was removed by the owner due to an interference with typescript auto-completion. However, there is a new version with only syntax highlighter.

See more : https://github.com/styled-components/vscode-styled-components#vscode-styled-components

**Comment by tohsaka888** [comment]
> No there is no mistake. The previous version of styled component plugin was removed by the owner due to an interference with typescript auto-completion. However, there is a new version with only syntax highlighter.
> 
> See more : https://github.com/styled-components/vscode-styled-components#vscode-styled-components


Thank you!
