### ISSUE TITLE
Does not support nested classes

### ISSUE THREAD

**Issue by kingdaro** [Microsoft/typescript-styled-plugin#2]
[As shown here](https://gfycat.com/AchingSophisticatedFritillarybutterfly), regular CSS properties work, but nested classes fail with a syntax error.
```ts
const Wrapper = styled.div`
  .some-class {
    /* etc */
  }
`
```

**Comment by Jipperism** [comment]
Would like to see if I can contribute to this, but the repo is not compiling for me at the moment. Fails with:

```src/logger.ts(4,26): error TS1005: ';' expected.
src/logger.ts(4,33): error TS1005: ';' expected.
src/logger.ts(5,12): error TS1005: ',' expected.
src/logger.ts(5,21): error TS1005: ';' expected.
src/logger.ts(5,27): error TS1109: Expression expected.```

**Comment by mjbvz** [comment]
@Jipperism I suspect the wrong version of tsc is being use. I just pushed bdbf23bcdbebd4570b223018551ed4e2b5dd0e15 which should ensure the compile script uses typescript 2.5.3 for building

As for actually fixing the issue, I suspect the easiest approach will be to use the sass language service instead of the regular css language service. This has the drawback of enabling other sass features in the styled strings but I'm not sure how often these would be hit. Let me know if you have any other ideas on how to fix this or if you have any questions about the code.

**Comment by Jipperism** [comment]
It is compiling now, but tests are not running. Is this still due to issue #11? I will look into using the sass language service.

**Comment by mjbvz** [comment]
Yes that #11. As a workaround, try manually installing `typescript@2.4.x` locally but compiling using a global version of typescript 2.5
