### ISSUE TITLE
Bug: Syntax error when interpolations come before other style properties

### ISSUE THREAD

**Issue by kingdaro** [Microsoft/typescript-styled-plugin#22]
Works when interpolating after:
![image](https://user-images.githubusercontent.com/19603573/32960081-bbe34700-cb91-11e7-9870-7982c390e78f.png)

Broken when interpolated before:
![image](https://user-images.githubusercontent.com/19603573/32960070-ad1156a4-cb91-11e7-983b-fdb649fb92c6.png)

Both are valid. Happy to provide more information if necessary 🙂

**Comment by mjbvz** [comment]
If anyone wants to take a look at this, the root cause is our replacement of placeholders so that the string looks like css to the css language service. Here's the current logic: https://github.com/Microsoft/typescript-styled-plugin/blob/master/src/index.ts#L38

**Comment by cchamberlain** [comment]
@mjbvz @kingdaro this plugin has been pretty crucial for my team, so though this issue isn't affecting me, I did some debugging.

Validated that the code posted in the issue above fails for me -

![image](https://user-images.githubusercontent.com/424694/33056915-f987a1c0-ce3c-11e7-8f2f-2816379a5d48.png)

The following works fine though -

![image](https://user-images.githubusercontent.com/424694/33056768-596b847c-ce3c-11e7-9f9b-e6b566f24d00.png)

Believe this is equivalent to what the parser is seeing when trying to strip my first example:

![image](https://user-images.githubusercontent.com/424694/33056876-d0c917b4-ce3c-11e7-9382-bd02c593a960.png)

Don't understand the template literal parser well enough to setup a test case myself this week, otherwise I'd attempt a fix.

Happy to fix this function if someone can point out a potential failing test case:

```tsx
getSubstitution(
        templateString: string,
        start: number,
        end: number
    ): string {
  const placeholder = templateString.slice(start, end);
  const pre = templateString.slice(0, start);
  const replacementChar = pre.match(/(^|\n)\s*$/g) ? ' ' : 'x';
  return placeholder.replace(/./gm, c => c === '\n' ? '\n' : replacementChar);
}
```

The placeholder line makes sense, but I'm kinda confused about what's going on in `pre` as well as what the `x` replacement is about. Would be happy to run with something like the following, if it's simple to provide:

```tsx
getSubstitution(`
  ${green};
  display: flex;
`, 5, 10) === "green"?
```

On a side note, every example of a mix-in style I've seen have included the semicolon in the generation, so guessing most aren't seeing this due to this being uncommon practice: https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md

**Comment by kingdaro** [comment]
For some background, I use the semicolon because prettier formats it correctly that way. I assumed it was the correct syntax because of this.
```js
// formatted with semicolon
const Container = styled.div`
	${fullscreen};
	width: 1200px;
	margin: auto;
`

// formatted without semicolon
const Container = styled.div`
  ${fullscreen} width: 1200px;
  margin: auto;
`
```

**Comment by cchamberlain** [comment]
@kingdaro thanks for context. That is a pretty nasty formatting choice prettier makes IMO. Feel like that would be annoying to deal with when forgetting a semi (if run on save) and seems like in worst case it would silently change the semantics.

Seems like a valid bug in both repos given that prettier mangles styled-component examples pulled from docs (assuming).

**Comment by kingdaro** [comment]
It looks like I managed to fix it. Working on a PR now
